name: Epic
description: Define a major project epic
title: "EPIC: "
labels: ["epic"]
body:
  - type: textarea
    id: outcome
    attributes:
      label: Desired outcome
      description: What should be true when this epic is complete?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is included?
    validations:
      required: true
  - type: textarea
    id: non-goals
    attributes:
      label: Non-goals
      description: What is explicitly excluded?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What must be demonstrably true?
    validations:
      required: true
