name: Task
description: Define an implementation task
title: "TASK: "
labels: ["task"]
body:
  - type: input
    id: work-packet
    attributes:
      label: Parent work packet
      placeholder: "WP-E0-001"
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: Task
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Done when
    validations:
      required: true
